query RepositoryDetails($repoId: ID!, $issuesLimit: Int!, $prsLimit: Int!) {
    node(id: $repoId) {
        ... on Repository {
            name
            issues(first: $issuesLimit) {
                nodes {
                    title
                    state
                }
            }
            pullRequests(first: $prsLimit) {
                nodes {
                    title
                    state
                }
            }
        }
    }
}

query GetUserRepositories($username: String!, $first: Int!) {
    user(login: $username) {
        repositories(first: $first) {
            nodes {
                id
                name
                url
            }
        }
    }
}